### ISSUE TITLE
Sending Keyboard signals via SimonRemote (for Netflix)

### ISSUE THREAD

**Issue by checketts** [SimonRemote/simon-mac#1]
I love controlling the my Mac via my pebble.  How difficult would it be to add an app profile for plain keyboard signals?

My main purpose would be to play/pause Netflix when across the room. It would assume Netflix already had focus and would just be sending a 'Space' signal.

**Comment by tyhoff** [comment]
Coming in a future update.

**Comment by tyhoff** [comment]
Done. Restart your client to get the update.

**Comment by checketts** [comment]
I can't seem to get this to work. On my Mac, the app I'm trying to use has focus if I hit the <SPACE> on my keyboard it does Play/Pause, but selecting Space on my Pebble doesn't seem to do anything.

Do I need to upgrade the app running on my Mac? I'll try that.

**Comment by checketts** [comment]
I can't seem to get this to work. On my Mac, the app I'm trying to use has focus if I hit the <SPACE> on my keyboard it does Play/Pause, but selecting Space on my Pebble doesn't seem to do anything.

Do I need to upgrade the app running on my Mac? I'll try that.

**Comment by checketts** [comment]
I did a manual upgrade on my Mac and now it works! Thanks!

**Comment by tyhoff** [comment]
whew, good news. Thanks for making sure it works.
